---

# 0. 
Ajout du compte user-ansible dans le groupe www-data
# pour la gestion des droits sur l'arborescence mediawiki
- name: "add user-ansible"
  command:
    usermod -a -G www-data user-ansible

#1. Création du répertoire pour l'installation des fichiers Mediawiki
- name: "mediawiki directory"
  file:
  path: "{{mediawiki_directory}}"
  owner: "www-data"
  group: "www-data"
  state: directory

#2. Décompresse le fichier source archive Mediawiki et le formate sans extension
- name: "uncompress mediawiki archive"
  unarchive:
    src: "{{mediawiki_archive_url}}"
    dest: "{{mediawiki_directory}}"
    owner: "www-data"
    group: "www-data"
    remote_src: yes
    ## supprime mediawiki-1.xx.x/ du chemin
    extra_opts: --transform=s/mediawiki-[0-9\.]*\///

#3. Ajoute les droits d'écriture pour le groupe www-data
- name: "add g+w sur le répertoire mediawiki"
  command:
    chmod -R g+w {{mediawiki_directory}}

#4. Exécute la tâche avec l'utilisateur ansible, se place dans le répertoire 
# de maintenance et éxécute la commande de configuration si le fichier 
# LocalSettings.php n'exsite pas
- name: mediawiki configuration"
  become: yes
  become_user: "user-ansible"
  args:
    creates: "{{mediawiki_directory}}/LocalSettings.php"
    chdir: "{{mediawiki_maintenance_directory}}"
  command:
    php install.php --scriptpath /{{mediawiki_name}}
    --dbname mediawiki --lang fr
    --dbuser {{mediawiki_db_user}}
    --dbpass {{mediawikki_db_password}}
    --pass {{mediawiki_admin_password}}
    --dbserver {{mediawiki_db_host}}
    --server http://http1
    {{mediawiki_title}} {{mediawiki_admin_user}}
  run_once: yes
  delegate_to: "{{item}}"
  with_items: "{{groups.apache}}"

#5. Exécute la tâche avec l'utilisateur ansible, se place dans le répertoire
# de maintenance et éxécute la commande de mise à jour de la base 
# unse seule fois 
- name: "mediawiki db update"
  become: yes
  become_user: "user-ansible"
  command:
    php update.php --quick
  args:
    chdir: "{{mediawiki_maintenance_directory}}"
  # La mise à jour à besoin d'être lancée une seule fois 
  run_once: yes
  register: resultat
  changed_when: "' ...done.' in resultat.stdout"



