---

# Base de données
mediawiki_db_name: "mediawiki"

# User et password
mediawiki_db_user: "mediawiki"
mediawiki_db_password: "{{ mediawiki_db_password }}"

# User admin et password
mediawiki_admin_user: "admin"
mediawiki_admin_password: "{{ mediawiki_admin_password }}"

# Nom du Mediawiki et de son titre 
mediawiki_name: "mediawiki"
mediawiki_title: "Mon super mediawiki"

# Répertoire d'installation
mediawiki_directory: "/var/www/html/{{mediawiki_name}}"

# Répertoire maintenance
mediawiki_maintenance_directory: "{{mediawiki_directory}}/maintenance"

# Définie le premier node du groupe mariadb
mediawiki_db_host: "{{ groups.db.0 }}"
# l'url des sources Mediawiki
mediawiki_archive_url: "https://releases.wikimedia.org/mediawiki/1.37/mediawiki-1.37.1.tar.gz"









